"""Generates real, valid Redshift DDL + COPY text from the DuckDB target
stand-in -- never executed against a real cluster (zero AWS SDK dependency,
fully unit-testable via string assertions). See docs/adr/001.
"""
import argparse
import os

from warehouse import config, db
from warehouse.advisor import recommend, USAGE_PROFILE

_TYPE_MAP = {
    "BIGINT": "BIGINT",
    "INTEGER": "INTEGER",
    "DOUBLE": "DOUBLE PRECISION",
    "BOOLEAN": "BOOLEAN",
    "DATE": "DATE",
    "TIMESTAMP": "TIMESTAMP",
}


def _redshift_type(con, table, column, duckdb_type):
    # ceiling: money/quantity measures built via a pandas round-trip in transform.py
    # lose DECIMAL precision to float64 (DuckDB<->pandas has no shared decimal type),
    # so they surface here as DOUBLE PRECISION -- a real migration would declare
    # DECIMAL(p,s) explicitly for those columns rather than trust the inferred type.
    if duckdb_type.startswith("DECIMAL"):
        return duckdb_type  # Redshift DECIMAL(p,s) syntax is identical
    if duckdb_type == "VARCHAR":
        max_len = con.execute(f"SELECT COALESCE(MAX(LENGTH({column})), 0) FROM analytics.{table}").fetchone()[0]
        length = max(16, max_len * 2)  # pad 2x observed max, floor of 16
        return f"VARCHAR({length})"
    return _TYPE_MAP.get(duckdb_type, duckdb_type)


def generate_ddl(con, table) -> str:
    columns = con.execute(f"DESCRIBE analytics.{table}").fetchdf()
    rec = recommend(con, table)

    col_lines = [
        f"    {row['column_name']} {_redshift_type(con, table, row['column_name'], row['column_type'])}"
        for _, row in columns.iterrows()
    ]

    ddl = f"CREATE TABLE analytics.{table} (\n" + ",\n".join(col_lines) + "\n)"
    ddl += f"\nDISTKEY({rec.distkey})" if rec.distkey else f"\nDISTSTYLE {rec.diststyle}"
    if rec.sortkey_columns:
        ddl += f"\n{rec.sortkey_type} SORTKEY({', '.join(rec.sortkey_columns)})"
    return ddl + ";\n"


def generate_copy(table) -> str:
    bucket = os.environ.get("TERRAPATH_S3_BUCKET", "terrapath-demo-bucket")
    role_arn = os.environ.get("TERRAPATH_IAM_ROLE_ARN", "arn:aws:iam::123456789012:role/terrapath-redshift-copy-role")
    return (
        f"COPY analytics.{table}\n"
        f"FROM 's3://{bucket}/exports/analytics/{table}/'\n"
        f"IAM_ROLE '{role_arn}'\n"
        f"FORMAT AS PARQUET;\n"
    )


def write_sql_file(table, ddl, copy_sql):
    config.GENERATED_SQL_DIR.mkdir(parents=True, exist_ok=True)
    path = config.GENERATED_SQL_DIR / f"{table}.sql"
    path.write_text(f"-- Generated by warehouse.ddl_generator. Never executed automatically.\n\n{ddl}\n{copy_sql}")
    return path


def run(con=None, table=None, all_tables=False):
    own_con = con is None
    con = con or db.get_target_connection()
    try:
        tables = list(USAGE_PROFILE) if (all_tables or not table) else [table]
        paths = []
        for t in tables:
            path = write_sql_file(t, generate_ddl(con, t), generate_copy(t))
            print(f"    [GENERATE] {path}")
            paths.append(path)
        return paths
    finally:
        if own_con:
            con.close()


def main():
    parser = argparse.ArgumentParser(description="Generate Redshift DDL + COPY text (never executed)")
    parser.add_argument("table", nargs="?", default=None)
    parser.add_argument("--all", action="store_true")
    args = parser.parse_args()
    run(table=args.table, all_tables=args.all)


if __name__ == "__main__":
    main()
